name: Post Ghost → Bsky

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"  # every day at 4 PM UTC

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post random Ghost blog to Bluesky
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          SITEMAP_URL: https://www.gojiberries.io/sitemap-posts.xml
        run: python scripts/post_random_ghost.py
